### ISSUE TITLE
Customize via args

### ISSUE THREAD

**Issue by JABvzla** [lucianomlima/react-native-template-basic#14]
You are willing to add options via args?. 
For example `react-native init [ProjectName] --template basic-app --skipFlow`.

Of course would like to contribute.

**Comment by lucianomlima** [comment]
The args passed to cli is for react-native-cli, nota template. Template itself os anexos arg to react-native. All dependencies are installed by react-native cli and template only finish the process deleting some files and organizing the rest.
Maybe it's possible to skip ir choose what to install through some user input system.

Enviado do Yahoo Mail no Android 
 
  <div>Em qui, 1 1e nov 1e 2018 às 23:09, JABvzla</div><div><notifications@github.com> escreveu:</div>   
You are willing to add options via args?.
For example react-native init [ProjectName] --template basic-app --skipFlow.

Of course would like to contribute.

**Comment by JABvzla** [comment]
Seeing it like that, my idea its something useless.

**Comment by lucianomlima** [comment]
It's possible, but I don't know If It's the best approach. Maybe will be better If react-native cli offer this decision to developers

Enviado do Yahoo Mail no Android 
 
  <div>Em qui, 1 1e nov 1e 2018 às 23:35, JABvzla</div><div><notifications@github.com> escreveu:</div>   
Seeing it like that, my idea its something useless.

**Comment by JABvzla** [comment]
Thanks, im gonna play with this.
